FROM jinaai/jina:2.6.2-py39-standard

# setup the workspace
COPY . /workspace
WORKDIR /workspace

RUN apt-get update && apt-get install --no-install-recommends -y git build-essential g++\
    && pip install -r requirements.txt

ENTRYPOINT ["python", "app.py", "-t", "search"]

EXPOSE 12345

LABEL name="jina-fashion-search-backend"
LABEL author="Jina AI Dev-Team (dev-team@jina.ai)"
LABEL type="app"
LABEL kind="example"
LABEL avatar="None"
LABEL description="Search fashion images using text (backend)"
LABEL documentation="https://github.com/alexcg1/jina-multimodal-fashion-search"
LABEL keywords="[fashion, cv, ecommerce, cross-modal, jina]"
LABEL license="apache-2.0"
LABEL platform="linux/amd64"
LABEL update="None"
LABEL url="https://github.com/alexcg1/jina-multimodal-fashion-search"
LABEL vendor="Jina AI Limited"
LABEL version="0.0.1"
